# pytorch基础

In [1]:
import torch

## Tensor

In [7]:
?torch.tensor

Docstring:
tensor(data, *, dtype=None, device=None, requires_grad=False, pin_memory=False) -> Tensor

Constructs a tensor with no autograd history (also known as a "leaf tensor", see :doc:`/notes/autograd`) by copying :attr:`data`.

.. warning::

    When working with tensors prefer using :func:`torch.Tensor.clone`,
    :func:`torch.Tensor.detach`, and :func:`torch.Tensor.requires_grad_` for
    readability. Letting `t` be a tensor, ``torch.tensor(t)`` is equivalent to
    ``t.clone().detach()``, and ``torch.tensor(t, requires_grad=True)``
    is equivalent to ``t.clone().detach().requires_grad_(True)``.

.. seealso::

    :func:`torch.as_tensor` preserves autograd history and avoids copies where possible.
    :func:`torch.from_numpy` creates a tensor that shares storage with a NumPy array.

Args:
    data (array_like): Initial data for the tensor. Can be a list, tuple,
        NumPy ``ndarray``, scalar, and other types.

Keyword args:
    dtype (:class:`torch.dtype`, optional): the de

### numpy导入

In [22]:
import numpy as np

a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:

b=torch.tensor(a)
b

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [24]:
c=torch.from_numpy(a)
c

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [25]:
c.numpy()

array([[1, 2, 3],
       [4, 5, 6]])

### tensor创建

In [27]:
a=torch.tensor(1.0,dtype=torch.float)
b=torch.tensor(1,dtype=torch.long)
c=torch.tensor(1.0,dtype=torch.int8)
print(a,b,c)

tensor(1.) tensor(1) tensor(1, dtype=torch.int8)


In [28]:
d=torch.FloatTensor(2,3)
print(d)
e=torch.IntTensor(2)
print(e)
f=torch.IntTensor([1,2,3])
print(f)
g=torch.IntTensor([[1,2,3],[4,5,6]])
print(g)
h=torch.IntTensor([[1,2,3],[4,5,[6,7,8]]])

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([         0, 2146435072], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32)
tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


TypeError: 'list' object cannot be interpreted as an integer

In [31]:
torch.rand(2,3)

tensor([[0.3645, 0.4124, 0.9537],
        [0.7838, 0.8331, 0.7241]])

In [32]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [33]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [34]:
torch.arange(0,10,1.5)

tensor([0.0000, 1.5000, 3.0000, 4.5000, 6.0000, 7.5000, 9.0000])

### 数值操作

In [35]:
i=torch.rand(2,4)
print(i.shape)
print(i.size())

torch.Size([2, 4])
torch.Size([2, 4])


In [42]:
j=torch.ones(2,3)
torch.add(j,0.1)

tensor([[1.1000, 1.1000, 1.1000],
        [1.1000, 1.1000, 1.1000]])

In [43]:
j.add(0.2)

tensor([[1.2000, 1.2000, 1.2000],
        [1.2000, 1.2000, 1.2000]])

In [44]:
j+0.3

tensor([[1.3000, 1.3000, 1.3000],
        [1.3000, 1.3000, 1.3000]])

### 索引、变形操作

In [50]:
a=torch.rand(2,3,4)
a

tensor([[[0.3749, 0.4705, 0.0487, 0.0029],
         [0.0492, 0.4116, 0.9138, 0.4899],
         [0.9083, 0.4960, 0.1101, 0.0913]],

        [[0.7666, 0.9895, 0.5800, 0.9769],
         [0.0062, 0.8873, 0.1436, 0.3698],
         [0.3303, 0.3743, 0.3654, 0.9944]]])

In [52]:
a[:,0]

tensor([[0.3749, 0.4705, 0.0487, 0.0029],
        [0.7666, 0.9895, 0.5800, 0.9769]])

In [54]:
a[0,:]

tensor([[0.3749, 0.4705, 0.0487, 0.0029],
        [0.0492, 0.4116, 0.9138, 0.4899],
        [0.9083, 0.4960, 0.1101, 0.0913]])

In [56]:
a[0,0,:]

tensor([0.3749, 0.4705, 0.0487, 0.0029])

In [57]:
a[0,0,0,:]

IndexError: too many indices for tensor of dimension 3

In [58]:
a.view(2,6,2)# 2*6*2=2*3*4

tensor([[[0.3749, 0.4705],
         [0.0487, 0.0029],
         [0.0492, 0.4116],
         [0.9138, 0.4899],
         [0.9083, 0.4960],
         [0.1101, 0.0913]],

        [[0.7666, 0.9895],
         [0.5800, 0.9769],
         [0.0062, 0.8873],
         [0.1436, 0.3698],
         [0.3303, 0.3743],
         [0.3654, 0.9944]]])

In [59]:
a.view(2,-1,2)# 自动计算-1为6

tensor([[[0.3749, 0.4705],
         [0.0487, 0.0029],
         [0.0492, 0.4116],
         [0.9138, 0.4899],
         [0.9083, 0.4960],
         [0.1101, 0.0913]],

        [[0.7666, 0.9895],
         [0.5800, 0.9769],
         [0.0062, 0.8873],
         [0.1436, 0.3698],
         [0.3303, 0.3743],
         [0.3654, 0.9944]]])

In [70]:
#广播
p=torch.arange(1,3)
print(p)
q=torch.arange(1,4).view(3,1)
print(q)

tensor([1, 2])
tensor([[1],
        [2],
        [3]])


In [71]:
p+q

tensor([[2, 3],
        [3, 4],
        [4, 5]])

### 其他操作

#### 拼接

In [105]:

p=torch.rand(3)
q=torch.rand(7)
torch.cat((p,q))

tensor([0.3028, 0.7024, 0.5282, 0.8879, 0.9901, 0.6682, 0.3422, 0.7159, 0.5729,
        0.0426])

#### 压缩Squeeze

去除与张量正交的维度，使用时只能对维度为1的进行修改,e.g:[2,1,3]压缩后为[2,3]

In [98]:
#squeeze 修改维度
o=torch.arange(1,13,1).view(3,1,4)
o

tensor([[[ 1,  2,  3,  4]],

        [[ 5,  6,  7,  8]],

        [[ 9, 10, 11, 12]]])

In [99]:
o.shape

torch.Size([3, 1, 4])

In [100]:
o=o.squeeze(1)
print(o.shape,'\n',o)

torch.Size([3, 4]) 
 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


In [101]:
o=o.unsqueeze(1)
print(o.shape,'\n',o)


torch.Size([3, 1, 4]) 
 tensor([[[ 1,  2,  3,  4]],

        [[ 5,  6,  7,  8]],

        [[ 9, 10, 11, 12]]])


In [102]:
o=o.unsqueeze(0)
print(o.shape,'\n',o)

torch.Size([1, 3, 1, 4]) 
 tensor([[[[ 1,  2,  3,  4]],

         [[ 5,  6,  7,  8]],

         [[ 9, 10, 11, 12]]]])


## 自动求导 

In [123]:
x1=torch.tensor(1.0,requires_grad=True)
x2=torch.tensor(2.0,requires_grad=True)
y=x1+x2*2
print(y)

tensor(5., grad_fn=<AddBackward0>)


In [124]:
y.requires_grad

True

In [125]:
print(x1.grad.data)

AttributeError: 'NoneType' object has no attribute 'data'

In [126]:
x1

tensor(1., requires_grad=True)

In [133]:
y=x1+x2*2
y.backward()
print(x1.grad.data)
print(x2.grad.data)

tensor(7.)
tensor(12.)


In [134]:
#梯度会累加
y=x1+x2*2
y.backward()
print(x1.grad.data)
print(x2.grad.data)

tensor(8.)
tensor(14.)


In [136]:
x1=torch.tensor(1.0,requires_grad=False)
x2=torch.tensor(2.0,requires_grad=False)
y=x1+x2*2
#无法反向传播
y.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn